name: IKYY AR Family
key: indo;Indo;INDO;IKYY;ikyy;KYY;kyy;JAWA;Jawa;jawa
color: black
emblem: flag_e_02
sort: trophy
info:
logo: https://drive.google.com/file/d/10enDGo63hlzqQ8g4xScXPA080deNgcLS/view?usp=sharing
description: >
** Family Team Clash Royale from Indonesia**
We accept players from beginner-to-high level experience who qualify
(Active Donation,Daily Clan Wars).We Start by familiarizing players
with the rules according to the standards of large clans.We also teach
beginners by opening frequently asked questions about Clash Royale in
clan conversations,open the test-assessment-suggestion deck on clan conversations.

social:
- facebook: https://www.facebook.com/AvinPalilingDC13/
- instagram: https://www.instagram.com/vinx177/
clans:

name: JAWA SQUADS
tag: 9GR9QPRJ
name: Indo KYY ARMY
tag: Q8CJCCCY
