```yaml
name: IKYY AR Family
key: indo;Indo;INDO;IKYY;ikyy;KYY;kyy;JAWA;Jawa;jawa
color: black
emblem: flag_e_02
sort: trophy
info:
logo: https://drive.google.com/file/d/1W9K3uw0_dLRFPx6FV0y4y6NjUKISudQv/view?usp=sharing
description: >
** IKKY AR & JSF**
** Family Team Clash Royale from Indonesia**
We accept players from beginner-to-high level experience who qualify
(Active Donation,Daily Clan Wars).We Start by familiarizing players
with the rules according to the standards of large clans.We also teach
beginners by opening frequently asked questions about Clash Royale in
clan conversations,open the test-assessment-suggestion deck on clan conversations.

social:
- facebook: https://www.facebook.com/AvinPalilingDC13/
- instagram: https://www.instagram.com/vinx177/
- email: mailto: les.017ciers@gmail.com
- linktree: https://linktr.ee/IKYY_AR_n_JSF
clans:

name: JAWA SQUADS
tag: 9GR9QPRJ
name: Indo KYY ARMY
tag: Q8CJCCCY
name: JAWA SQUADS II
tag: LR82UUPJ
name: AVIN PALILING
tag: YUVP9GCU
```
